// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtRom_V6WBVmW90dOiUJJNgdr3IgRmVNc',
    appId: '1:398017566208:android:efa2d179021a177a45aae5',
    messagingSenderId: '398017566208',
    projectId: 'minhasaudefeminina-5f28c',
    storageBucket: 'minhasaudefeminina-5f28c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa5LxyyhXKx5br-VPMqv5-A_VsBS97pXk',
    appId: '1:398017566208:ios:57d0816a7d3483c245aae5',
    messagingSenderId: '398017566208',
    projectId: 'minhasaudefeminina-5f28c',
    storageBucket: 'minhasaudefeminina-5f28c.firebasestorage.app',
    androidClientId: '398017566208-5botji0v7bprfr2ndg01tot4tbre2h95.apps.googleusercontent.com',
    iosClientId: '398017566208-3ldpttchb91bbjpgou8c8nsm9on5gq83.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

}