# Dialeto para acesso ao banco
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Acesso ao banco Oracle
spring.datasource.url=jdbc:oracle:thin:@${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_SERVICE_NAME}
spring.datasource.username=${ORACLE_USER}
spring.datasource.password=${ORACLE_PASSWORD}

# Acesso ao Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# Comunicação do backend com Firebase
firebase.service-account-path=classpath:firebase-service-account.json
